apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
      - name: haproxy
        image: haproxy:latest
        volumeMounts:
        - name: config-volume
          mountPath: /usr/local/etc/haproxy
        ports:
        - name: mysql
          containerPort: 3306
        - name: http
          containerPort: 80
      volumes:
      - name: config-volume
        configMap:
          name: haproxy-config
