apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
  namespace: default
data:
  haproxy.cfg: |
    global
        log stdout format raw local0
        maxconn 4000
    defaults
        log     global
        mode    tcp
        option  tcplog
        timeout connect 5000ms
        timeout client  50000ms
        timeout server  50000ms
    frontend mysql_front
        bind *:3306
        default_backend mysql_back
    backend mysql_back
        balance roundrobin
        option tcp-check
        tcp-check connect
        tcp-check send-binary 0100000001      # MySQL COM_QUIT command
        server galera0 my-release-mariadb-galera-0.my-release-mariadb-galera-headless.default.svc.cluster.local:3306 check inter 1000 rise 2 fall 3
        server galera1 my-release-mariadb-galera-1.my-release-mariadb-galera-headless.default.svc.cluster.local:3306 check inter 1000 rise 2 fall 3 backup
        server galera2 my-release-mariadb-galera-2.my-release-mariadb-galera-headless.default.svc.cluster.local:3306 check inter 1000 rise 2 fall 3 backup
    frontend http_front
        bind *:8080
        default_backend zabbix_web_back
    backend zabbix_web_back
        balance roundrobin
        option httpchk GET /index.php
        http-check expect status 200
        server zabbix-web1 release-name-zabbix-zabbix-web.default.svc.cluster.local:80 check
