apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-my-release-mariadb-galera-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: managed-premium
