apiVersion: v1
kind: Service
metadata:
  name: haproxy-deployment
  namespace: default
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
    - name: http
      port: 8080 # Expose the non-privileged port
      targetPort: 8080 # Target the same port inside the pod
      protocol: TCP
  selector:
    app: haproxy
